# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57ca61d65892fb7f3adc962f590a67a347d95df28b8b3703444ed3cbff288ef54275bf31fc830d75dd0b02dcd1507838cc43f877f92508b11782ac802ba48e24

test:
  secret_key_base: db1b399a3156740a5507df09d9d2affb4225f493082e306cf202a201e5713b7c43b084bb50428aa14cf9edc1f7adf06825967f080db1c1051752c3af02f2bd30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
